set dotenv-load := true

default:
  just --list

##############################
# utils

clippy:
  cargo clippy -- -Aclippy::drop_non_drop

clippy-mac:
  cd ./node-manager && AR=/opt/homebrew/opt/llvm/bin/llvm-ar CC=/opt/homebrew/opt/llvm/bin/clang cargo clippy -- -Aclippy::drop_non_drop

create-cert:
  ./create_cert.sh

##############################
# wallet-blockchain-interface

build-wbi:
  cd ./wallet-blockchain-interface && npm i && npm run build

wbi: build-wbi
  cd ./wallet-blockchain-interface && npm run start


##############################
# wallet

build-wallet:
  cargo build --release --bin dlc-protocol-wallet --target-dir .

generate-key:
  cargo build --release --bin generate-key --target-dir .
  ./release/generate-key

generate-address-from-key:
  cargo build --release --bin generate-address-from-key --target-dir .
  ./release/generate-address-from-key

wallet: build-wallet
  ./release/dlc-protocol-wallet

##############################
# both

build: build-wbi build-wallet

run: build
  just wbi &
  just wallet && fg
