build:
  cargo build --release --bins --target-dir .

generate-key: build
  ./release/generate-key

wallet: build
  ./release/dlc-protocol-wallet

generate-address-from-key: build
  ./release/generate-address-from-key

clippy:
  cargo clippy -- -Aclippy::drop_non_drop

clippy-mac:
  cd ./node-manager && AR=/opt/homebrew/opt/llvm/bin/llvm-ar CC=/opt/homebrew/opt/llvm/bin/clang cargo clippy -- -Aclippy::drop_non_drop
