FROM rustlang/rust:nightly-buster AS build

# Build Rust app
COPY ./wallet/src /app/dlc-protocol-wallet/src
COPY ./wallet/Cargo.toml /app/dlc-protocol-wallet/Cargo.toml
COPY ./dlc-link-manager /app/dlc-link-manager/
COPY ./clients /app/clients/
COPY ./attestor-client /app/attestor-client/
COPY ./dlc-wallet /app/dlc-wallet/
COPY ./esplora-async-blockchain-provider-js-wallet /app/esplora-async-blockchain-provider-js-wallet/
COPY ./esplora-async-blockchain-provider-router-wallet /app/esplora-async-blockchain-provider-router-wallet/
COPY ./js-interface-wallet /app/js-interface-wallet/

WORKDIR /app/dlc-protocol-wallet/

RUN cargo build --release --bin generate-key --target-dir .
RUN cargo build --release --bin generate-address-from-key --target-dir .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y openssl libpq-dev ca-certificates

COPY --from=build /app/dlc-protocol-wallet/release/generate-key /app/dlc-protocol-wallet/release/generate-key
COPY --from=build /app/dlc-protocol-wallet/release/generate-address-from-key /app/dlc-protocol-wallet/release/generate-address-from-key

WORKDIR /app/dlc-protocol-wallet/release/

RUN chmod +x ./generate-key ./generate-address-from-key

CMD [ "/bin/bash" ]
