settings:
  # The dlc-solidity branch contract deployment infos will be fetched from
  solidity-branch: dev
  # Endpoint for CET Storage API
  storage-api-endpoint: http://127.0.0.1:8100
  # Developer endpoints
  dev-endpoints-enabled: true

# Chain configurations
# Uncomment/edit the chains you want to use
#
#  - network: <network name> (required) - see supported chains in ./observer/src/config/models.ts
#    version: <contract version> (optional) - currently only version is default: 1
#    endpoint: <chain endpoint> (optional) - RPC/WS endpoint for the chain, see ./observer/src/config/network-configs.ts for defaults
#    api_key: <api key> (optional) - API key for the provider, see ./observer/src/config/network-configs.ts for defaults

# Supported evm-chains: mainnet, sepolia, goerli, localhost, x1test
evm-chains:
  # L1 mainnet is not supported yet!
  # - network: mainnet
  #   version: 1
  #   endpoint: wss://mainnet.infura.io/ws/v3/
  #   api_key: ${INFURA_API_KEY}

  # This is how a setup looks that uses a local node,
  # but the 'sepolia' contracts from dlc-solidity
  # - network: sepolia
  #   version: 1
  #   endpoint: http://localhost:8545
  #   # endpoint: wss://sepolia.infura.io/ws/v3/
  #   # api_key: ${INFURA_API_KEY}

  # - network: goerli
  #   version: 1
  #   endpoint: wss://goerli.infura.io/ws/v3/
  #   api_key: ${INFURA_API_KEY}

  # # - network: localhost
  # #   version: '1'
  # #   endpoint: http://localhost:8545

  # # OKX testnet
  # - network: x1test
  #   version: 1
  #   endpoint: wss://x1testws.okx.com

stx-chains:
  # - network: mainnet
  #   version: 1
  #   deployer:
  #   endpoint: wss://api.hiro.so/

  # - network: testnet
  #   version: 1
  #   deployer: ST1JHQ5GPQT249ZWG6V4AWETQW5DYA5RHJB0JSMQ3
  #   endpoint: wss://api.testnet.hiro.so/

  # - network: mocknet
  #   version: 1
  #   deployer: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
  #   endpoint: ws://45.79.130.153:3999

  - network: local
    version: 1
    deployer: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
    endpoint: ws://localhost:3999
