settings:
  # The dlc-solidity branch contract deployment infos will be fetched from
  # solidity-branch: dev
  # For Bitcoin testnet:
  solidity-branch: master

  # Endpoint for CET Storage API
  # storage-api-endpoint: https://devnet.dlc.link/storage-api
  # For Bitcoin testnet:
  storage-api-endpoint: https://testnet.dlc.link/storage-api
  # For local development:
  # storage-api-endpoint: http://127.0.0.1:8100

  # Developer endpoints
  dev-endpoints-enabled: false

# Chain configurations
# Uncomment/edit the chains you want to use
#
#  - network: <network name> (required) - see supported chains in ./observer/src/config/models.ts
#    version: <contract version> (optional) - currently only version is default: 1
#    endpoint: <chain endpoint> (optional) - RPC/WS endpoint for the chain, see ./observer/src/config/network-configs.ts for defaults
#    api_key: <api key> (optional) - API key for the provider, see ./observer/src/config/network-configs.ts for defaults

# Supported evm-chains: mainnet, sepolia, goerli, localhost, x1test
evm-chains:
  # L1 mainnet is not supported yet!
  # - network: mainnet
  #   version: 1
  #   endpoint: wss://mainnet.infura.io/ws/v3/
  #   api_key: ${INFURA_API_KEY}

  # This configuration will load our sepolia contracts, listening on a local node
  - network: sepolia
    version: 1
    # Local Ethereum node
    endpoint: http://localhost:8545
    # Or using Infura:
    # endpoint: wss://sepolia.infura.io/ws/v3/
    # api_key: ${INFURA_API_KEY}

  - network: goerli
    version: 1
    endpoint: http://localhost:8546
  #   endpoint: wss://goerli.infura.io/ws/v3/
  #   api_key: ${INFURA_API_KEY}

  # - network: localhost
  #   version: '1'
  #   endpoint: http://localhost:8545

  # # OKX testnet
  # - network: x1test
  #   version: 1
  #   endpoint: wss://x1testws.okx.com

stx-chains:
  # - network: mainnet
  #   version: 1
  #   deployer:
  #   endpoint: wss://api.hiro.so/

  # - network: testnet
  #   version: 1
  #   deployer: ST1JHQ5GPQT249ZWG6V4AWETQW5DYA5RHJB0JSMQ3
  #   endpoint: wss://api.testnet.hiro.so/

  # - network: mocknet
  #   version: 1
  #   deployer: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
  #   endpoint: ws://stx-btc1.dlc.link:3999

  # - network: local
  #   version: 1
  #   deployer: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
  #   endpoint: ws://localhost:3999
