set dotenv-load := true

default:
  just --list

build:
  cd observer && ./build_all.sh

run:
  cd observer && ./start_attestor.sh

run-multiple:
  cd observer && npm run run:1 &
  cd observer && npm run run:2 &
  cd observer && npm run run:3 && fg
