settings:
  solidity-branch: dev
  storage-api-endpoint: http://storageapi:8100
  dev-endpoints-enabled: true

evm-chains:

stx-chains:
  - network: mocknet
    version: 1
    deployer: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
    endpoint: ws://45.79.130.153:3999
