set dotenv-load := true

default:
  just --list

run-wallet:
  cd ../wallet && just run

run-attestors:
  cd ../attestor && just run-multiple

run-storage:
  cd ../storage && just run

build-wasm:
  npm run build

the-script:
  ENV=local_just HANDLE_ATTESTORS=true npm start && wait

alias it := run
alias run-it := run
alias doit := run
alias do-it := run

run:
  just build-wasm && wait
  just run-storage &
  just run-attestors &
  just run-wallet &
  while ! nc -z localhost 8085; do sleep 1; done
  ENV=local_just HANDLE_ATTESTORS=true npm start && wait
  just die

die:
  lsof -t -i:3000 2>/dev/null | xargs -r kill
  lsof -t -i:3001 2>/dev/null | xargs -r kill
  lsof -t -i:8801 2>/dev/null | xargs -r kill
  lsof -t -i:8802 2>/dev/null | xargs -r kill
  lsof -t -i:8803 2>/dev/null | xargs -r kill
  lsof -t -i:8100 2>/dev/null | xargs -r kill
  lsof -t -i:8085 2>/dev/null | xargs -r kill
